# Generated by Django 4.2.7 on 2023-11-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('userInfoId', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.CharField(max_length=100)),
                ('userPassword', models.CharField(max_length=100)),
            ],
        ),
    ]
